# Generated by Django 2.2.6 on 2019-10-20 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_app', '0002_auto_20191020_1004'),
        ('worker_app', '0001_initial'),
        ('general_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeJobWorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('ratings', models.IntegerField()),
                ('review', models.TextField()),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.JeJob')),
                ('work_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.JeWorkStatus')),
            ],
        ),
        migrations.CreateModel(
            name='JeJobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apply_date', models.DateTimeField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.JeJob')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.JeWorker')),
            ],
        ),
    ]
