# Generated by Django 2.2.6 on 2019-10-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_app', '0001_initial'),
        ('buyer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JeWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(max_length=1000)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer_app.ScUser')),
            ],
        ),
        migrations.CreateModel(
            name='JeWorkerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.JeSkill')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.JeWorker')),
            ],
        ),
        migrations.CreateModel(
            name='JeWorkerPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=1000)),
                ('attachment', models.FileField(upload_to='')),
                ('image', models.FileField(upload_to='')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.JeWorker')),
            ],
        ),
        migrations.CreateModel(
            name='JeWorkerCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.JeCertification')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.JeWorker')),
            ],
        ),
    ]
