# Generated by Django 2.2.6 on 2019-10-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JeDurationUnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_unit_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JeJobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JeRateUnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_unit_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JeSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=100)),
                ('categoty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.JeCategory')),
            ],
        ),
        migrations.CreateModel(
            name='JeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_tytle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('rate_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apply_deadline', models.DateTimeField()),
                ('post_date', models.DateTimeField()),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer_app.JeBuyer')),
                ('duration_unit_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.JeDurationUnitType')),
                ('job_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.JeJobType')),
                ('rate_unit_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.JeRateUnitType')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.JeSubCategory')),
            ],
        ),
    ]
