# Generated by Django 2.2.6 on 2019-10-20 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jesubcategory',
            name='categoty_id',
        ),
        migrations.AlterField(
            model_name='jejob',
            name='duration_unit_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.JeDurationUnitType'),
        ),
        migrations.AlterField(
            model_name='jejob',
            name='job_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.JeJobType'),
        ),
        migrations.AlterField(
            model_name='jejob',
            name='rate_unit_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.JeRateUnitType'),
        ),
        migrations.AlterField(
            model_name='jejob',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.JeSubCategory'),
        ),
        migrations.DeleteModel(
            name='JeCategory',
        ),
        migrations.DeleteModel(
            name='JeDurationUnitType',
        ),
        migrations.DeleteModel(
            name='JeJobType',
        ),
        migrations.DeleteModel(
            name='JeRateUnitType',
        ),
        migrations.DeleteModel(
            name='JeSubCategory',
        ),
    ]
