# Generated by Django 2.2.6 on 2019-10-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0001_initial'),
        ('job_app', '0002_auto_20191020_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jejob',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='JeJobSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.JeJob')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.JeSkill')),
            ],
        ),
        migrations.CreateModel(
            name='JeJobAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.JeJob')),
            ],
        ),
    ]
